/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Backend.service;

import Backend.entities.TUsers;
import java.util.Collection;
import java.util.List;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

/**
 *
 * @author fauzianordlund
 * The TUsersFacadeREST is used to handle transactions to the database 
 * concerning the TUsers entity. Apart from the autogenerated methods to 
 * create, find, edit and delete entities there are methods to login a user 
 * and finding users with a username containing a specific searchString. 
 */
@Stateless
@Path("entities.tusers")
public class TUsersFacadeREST extends AbstractFacade<TUsers> {

    @PersistenceContext(unitName = "12-17PU")
    private EntityManager em;

    public TUsersFacadeREST() {
        super(TUsers.class);
    }

    @POST
    @Override
    @Consumes({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
    public void create(TUsers entity) {
        super.create(entity);
    }

    @PUT
    @Path("{id}")
    @Consumes({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
    public void edit(@PathParam("id") Long id, TUsers entity) {
        super.edit(entity);
    }

    @DELETE
    @Path("{id}")
    public void remove(@PathParam("id") Long id) {
        super.remove(super.find(id));
    }

    @GET
    @Path("{id}")
    @Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
    public TUsers find(@PathParam("id") Long id) {
        return super.find(id);
    }

    @GET
    @Produces({MediaType.APPLICATION_XML,MediaType.APPLICATION_JSON})
    public List<TUsers> findAll() {
   
        return super.findAll();
    }

    @GET
    @Path("{from}/{to}")
    @Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
    public List<TUsers> findRange(@PathParam("from") Integer from, @PathParam("to") Integer to) {
        return super.findRange(new int[]{from, to});
    }

    @GET
    @Path("count")
    @Produces(MediaType.TEXT_PLAIN)
    public String countREST() {
        return String.valueOf(super.count());
    }
    
    @GET
    @Path("/login/{username}/{password}")
    @Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
    public TUsers login(@PathParam("username") String username, @PathParam("password") String password) {
        em = getEntityManager();
        Query q = em.createNamedQuery("TUsers.findByUsername");
        q.setParameter("username", username);
        return (TUsers) q.getSingleResult();
    }
    
    @GET
    @Path("/getUsersByContains/{searchString}")
    @Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
    public Collection<TUsers> getUsersByContains(@PathParam("searchString") String searchString) {
        EntityManager em = getEntityManager();
        Query q = em.createNamedQuery("TUsers.findByContains");
        q.setParameter("searchString", "%" + searchString + "%");
        Collection<TUsers> tmp = q.getResultList();
        return tmp;
    }

    @Override
    protected EntityManager getEntityManager() {
        return em;
    }
    
}
