/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend.Clients;

import javax.ws.rs.ClientErrorException;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.GenericType;
import javax.ws.rs.core.Response;

/**
 * Jersey REST client generated for REST resource:TMessagesFacadeREST
 * [entities.tmessages]<br>
 * USAGE:
 * <pre>
 *        MessageClient client = new MessageClient();
 *        Object response = client.XXX(...);
 *        // do whatever with response
 *        client.close();
 * </pre>
 *
 * @author Niklas
 * The MessageClient is used to conveniently make calls to the REST services located at
 * http://localhost:8080/SocialmediaBackendREST/webresources/entities.tmessage. 
 * Most methods have support to use either XML or JSON to exchange information, 
 * plain text is used in some cases. Most methods are autogenerated to support such
 * functions as create, find, edit and delete entities. A few are, however, created to support
 * features such as finding message from a specific sender or to a specific receiver. Some methods 
 * require a GenericType<T> to be provided as the returnType. It may be a good idea to create 
 * a viewmodel TMessages including Long id, boolean isDeleted, boolean isRead, String messageText, 
 * Date timeSent, TUsers receiverid, TUsers senderid to be used as a return type. 
 */
public class MessageClient {

    private WebTarget webTarget;
    private Client client;
    private static String localhost = "http://localhost:8080";
    private static String dockerhost = "http://192.168.99.100:8080"; //5432
    private static String cloudhost = "http://nodejsmessages-dot-vital-valor-188709.appspot.com";
    private static final String BASE_URI = cloudhost+"/SocialmediaMicro";

    public MessageClient() {
        client = javax.ws.rs.client.ClientBuilder.newClient();
        webTarget = client.target(BASE_URI).path("entities.tmessages");
    }

    public String countREST() throws ClientErrorException {
        WebTarget resource = webTarget;
        resource = resource.path("count");
        return resource.request(javax.ws.rs.core.MediaType.TEXT_PLAIN).get(String.class);
    }

    public void edit_XML(Object requestEntity, String id) throws ClientErrorException {
        webTarget.path(java.text.MessageFormat.format("{0}", new Object[]{id})).request(javax.ws.rs.core.MediaType.APPLICATION_XML).put(javax.ws.rs.client.Entity.entity(requestEntity, javax.ws.rs.core.MediaType.APPLICATION_XML));
    }

    public void edit_JSON(Object requestEntity, String id) throws ClientErrorException {
        webTarget.path(java.text.MessageFormat.format("{0}", new Object[]{id})).request(javax.ws.rs.core.MediaType.APPLICATION_JSON).put(javax.ws.rs.client.Entity.entity(requestEntity, javax.ws.rs.core.MediaType.APPLICATION_JSON));
    }

    public <T> T find_XML(GenericType<T> responseType, String id) throws ClientErrorException {
        WebTarget resource = webTarget;
        resource = resource.path(java.text.MessageFormat.format("{0}", new Object[]{id}));
        return resource.request(javax.ws.rs.core.MediaType.APPLICATION_XML).get(responseType);
    }

    public <T> T find_JSON(GenericType<T> responseType, String id) throws ClientErrorException {
        WebTarget resource = webTarget;
        resource = resource.path(java.text.MessageFormat.format("{0}", new Object[]{id}));
        return resource.request(javax.ws.rs.core.MediaType.APPLICATION_JSON).get(responseType);
    }

    public <T> T findRange_XML(GenericType<T> responseType, String from, String to) throws ClientErrorException {
        WebTarget resource = webTarget;
        resource = resource.path(java.text.MessageFormat.format("{0}/{1}", new Object[]{from, to}));
        return resource.request(javax.ws.rs.core.MediaType.APPLICATION_XML).get(responseType);
    }

    public <T> T findRange_JSON(GenericType<T> responseType, String from, String to) throws ClientErrorException {
        WebTarget resource = webTarget;
        resource = resource.path(java.text.MessageFormat.format("{0}/{1}", new Object[]{from, to}));
        return resource.request(javax.ws.rs.core.MediaType.APPLICATION_JSON).get(responseType);
    }

    /**
     * This method will set the IsRead value to true on a message using XML.
     * @param requestEntity The message which IsRead is to be set to true.
     * @throws ClientErrorException 
     */
    public void setMessageToIsRead_XML(Object requestEntity) throws ClientErrorException {
        webTarget.path("setMessageToIsRead").request(javax.ws.rs.core.MediaType.APPLICATION_XML).post(javax.ws.rs.client.Entity.entity(requestEntity, javax.ws.rs.core.MediaType.APPLICATION_XML));
    }

    /**
     * This method will set the IsRead value to true on a message using JSON.
     * @param requestEntity The message which IsRead is to be set to true.
     * @throws ClientErrorException 
     */
    public void setMessageToIsRead_JSON(Object requestEntity) throws ClientErrorException {
        webTarget.path("setMessageToIsRead").request(javax.ws.rs.core.MediaType.APPLICATION_JSON).post(javax.ws.rs.client.Entity.entity(requestEntity, javax.ws.rs.core.MediaType.APPLICATION_JSON));
    }

    public void create_XML(Object requestEntity) throws ClientErrorException {
        webTarget.request(javax.ws.rs.core.MediaType.APPLICATION_XML).post(javax.ws.rs.client.Entity.entity(requestEntity, javax.ws.rs.core.MediaType.APPLICATION_XML));
    }

    public void create_JSON(Object requestEntity) throws ClientErrorException {
        webTarget.request(javax.ws.rs.core.MediaType.APPLICATION_JSON).post(javax.ws.rs.client.Entity.entity(requestEntity, javax.ws.rs.core.MediaType.APPLICATION_JSON));
    }

    /**
     * This method is used to find all messages sent to a specific receiver using XML.
     * @param responseType A GenericType<T> of which type the returnvalue should be of.
     * @param receiver_id The ID of the receiver of the message.
     * @return A list of all messages sent from one sender to one receiver.
     * @throws ClientErrorException 
     */
    public <T> T getMessagesFromAll_XML(GenericType<T> responseType, String receiver_id) throws ClientErrorException {
        WebTarget resource = webTarget;
        resource = resource.path(java.text.MessageFormat.format("getMessagesFromAll/{0}", new Object[]{receiver_id}));
        return resource.request(javax.ws.rs.core.MediaType.APPLICATION_XML).get(responseType);
    }
    
    /**
     * This method is used to find all messages sent to a specific receiver using JSON.
     * @param responseType A GenericType<T> of which type the returnvalue should be of.
     * @param receiver_id The ID of the receiver of the message.
     * @return A list of all messages sent from one sender to one receiver.
     * @throws ClientErrorException 
     */
    public <T> T getMessagesFromAll_JSON(GenericType<T> responseType, String receiver_id) throws ClientErrorException {
        WebTarget resource = webTarget;
        resource = resource.path(java.text.MessageFormat.format("getMessagesFromAll/{0}", new Object[]{receiver_id}));
        return resource.request(javax.ws.rs.core.MediaType.APPLICATION_JSON).get(responseType);
    }

    public <T> T findAll_JSON(GenericType<T> responseType) throws ClientErrorException {
        WebTarget resource = webTarget;
        return resource.request(javax.ws.rs.core.MediaType.APPLICATION_JSON).get(responseType);
    }

    public <T> T findAll_TEXT(GenericType<T> responseType) throws ClientErrorException {
        WebTarget resource = webTarget;
        return resource.request(javax.ws.rs.core.MediaType.TEXT_PLAIN).get(responseType);
    }

    public void remove(String id) throws ClientErrorException {
        webTarget.path(java.text.MessageFormat.format("{0}", new Object[]{id})).request().delete();
    }
    
    /**
     *  This method is used to retrieve messages from a specific sender to a specific receiver using XML.
     * @param responseType A GenericType<T> of which type the returnvalue should be of.
     * @param receiver_id The ID of the receiver of the message.
     * @param sender_id The ID of the sender of the message.
     * @return A list of all messages sent from one sender to one receiver.
     * @throws ClientErrorException 
     */
    public <T> T getMessagesFromOneSender_XML(GenericType<T> responseType, String receiver_id, String sender_id) throws ClientErrorException {
        WebTarget resource = webTarget;
        resource = resource.path(java.text.MessageFormat.format("getMessagesFromOneSender/{0}/{1}", new Object[]{receiver_id, sender_id}));
        return resource.request(javax.ws.rs.core.MediaType.APPLICATION_XML).get(responseType);
    }

    /**
     *  This method is used to retrieve messages from a specific sender to a specific receiver using JSON.
     * @param responseType A GenericType<T> of which type the returnvalue should be of.
     * @param receiver_id The ID of the receiver of the message.
     * @param sender_id The ID of the sender of the message.
     * @return A list of all messages sent from one sender to one receiver.
     * @throws ClientErrorException 
     */
    public <T> T getMessagesFromOneSender_JSON(GenericType<T> responseType, String receiver_id, String sender_id) throws ClientErrorException {
        WebTarget resource = webTarget;
        resource = resource.path(java.text.MessageFormat.format("getMessagesFromOneSender/{0}/{1}", new Object[]{receiver_id, sender_id}));
        return resource.request(javax.ws.rs.core.MediaType.APPLICATION_JSON).get(responseType);
    }

    public void close() {
        client.close();
    }
    
}
