runtime : custom
env : flex

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

env_variables:
  SQL_USER: root
  SQL_PASSWORD: root
  SQL_DATABASE: socialmedia
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: vital-valor-188709:europe-west2:social-media

beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: vital-valor-188709:europe-west2:social-media